name: CI

on: [ push ]

jobs:
  tests:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.1, 8.2, 8.3, 8.4 ]
        contao: [ 4.13.*, 5.3.*, 5.5.* ]

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, pcre, pdo, zlib
          tools: phpunit
          coverage: none

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install the dependencies
        id: composer-install
        run: composer require contao/core-bundle:${{ matrix.contao }} contao/test-case:${{ matrix.contao }}  --no-interaction

      - name: Run the unit tests
        if: steps.composer-install.conclusion == 'success' && steps.composer-install.outcome == 'success'
        run: php vendor/bin/phpunit -c phpunit.xml.dist --colors=always

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, pcre, pdo, zlib
          coverage: xdebug
          tools: php-cs-fixer, phpunit

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install the dependencies
        run: composer require contao/core-bundle:4.13.* contao/test-case:4.13.* --no-interaction

      - name: Generate the coverage report
        run: php vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

      - name: Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=build/logs/clover.xml -v

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install the dependencies
        uses: ramsey/composer-install@v3

      - name: PHPStan
        run: vendor/bin/phpstan analyse -c phpstan.neon

  rector:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install the dependencies
        uses: ramsey/composer-install@v3

      - name: Rector
        run: vendor/bin/rector --dry-run --no-progress-bar